{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "5049d0b4-fe0d-4e75-8122-4f4766b41d5e",
   "metadata": {},
   "source": [
    "Q1. Explain why we have to use the Exception class while creating a Custom Exception.\n",
    "Note: Here Exception class refers to the base class for all the exceptions.\n",
    "\n",
    "ANS:\n",
    "\n",
    "In Python, when creating a custom exception, it is recommended to derive your custom exception class from the Exception class (or one of its subclasses) for several important reasons:\n",
    "\n",
    "1. Consistency with Built-in Exceptions: Python has a rich hierarchy of built-in exception classes, and they all inherit from the BaseException or Exception class. This hierarchy provides a consistent way to handle and categorize exceptions. When you create a custom exception that inherits from the Exception class, it aligns with this established convention and ensures that your custom exception is treated like other exceptions in Python.\n",
    "\n",
    "2. Exception Handling: Deriving from the Exception class allows your custom exception to be caught and handled using the same mechanisms that handle other exceptions. This means you can use try-except blocks to catch your custom exception just like you would for built-in exceptions. It also makes it easier for developers to understand how to handle your custom exception because they can follow the same patterns they use for other exceptions.\n",
    "\n",
    "3. Clarity and Documentation: Deriving from Exception or a related subclass provides a clear indication that your class represents an exception. It serves as a form of self-documentation, making it obvious to other developers that the class is meant to be used for error conditions. This can improve the readability and maintainability of your code.\n",
    "\n",
    "4. Compatibility: Python's exception handling mechanisms are designed to work with classes that inherit from Exception. If you create a custom exception that doesn't inherit from it, you may encounter unexpected behavior when trying to catch or handle the exception using standard Python exception handling constructs."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 26,
   "id": "6352117e-593e-42c8-9ad5-105099ef11c5",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Caught custom exception: This is a custom exception.\n"
     ]
    }
   ],
   "source": [
    "class CustomError(Exception):\n",
    "    def __init__(self, message):\n",
    "        super().__init__(message)\n",
    "\n",
    "try:\n",
    "    raise CustomError(\"This is a custom exception.\")\n",
    "except CustomError as e:\n",
    "    print(\"Caught custom exception:\", e)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "584762b7-aca5-43a5-aeef-336770f990f2",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "markdown",
   "id": "a2dd8ea7-6f7c-4d96-833f-d309bbf53d30",
   "metadata": {},
   "source": [
    "Q2. Write a python program to print Python Exception Hierarchy.\n",
    "\n",
    "ANS:\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 29,
   "id": "37417372-5d71-4caa-a2dc-9606f6c91c59",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Python Exception Hierarchy:\n",
      "BaseException\n",
      "  Exception\n",
      "    TypeError\n",
      "      FloatOperation\n",
      "      MultipartConversionError\n",
      "    StopAsyncIteration\n",
      "    StopIteration\n",
      "    ImportError\n",
      "      ModuleNotFoundError\n",
      "      ZipImportError\n",
      "    OSError\n",
      "      ConnectionError\n",
      "        BrokenPipeError\n",
      "        ConnectionAbortedError\n",
      "        ConnectionRefusedError\n",
      "        ConnectionResetError\n",
      "          RemoteDisconnected\n",
      "      BlockingIOError\n",
      "      ChildProcessError\n",
      "      FileExistsError\n",
      "      FileNotFoundError\n",
      "      IsADirectoryError\n",
      "      NotADirectoryError\n",
      "      InterruptedError\n",
      "        InterruptedSystemCall\n",
      "      PermissionError\n",
      "      ProcessLookupError\n",
      "      TimeoutError\n",
      "      UnsupportedOperation\n",
      "      itimer_error\n",
      "      herror\n",
      "      gaierror\n",
      "      SSLError\n",
      "        SSLCertVerificationError\n",
      "        SSLZeroReturnError\n",
      "        SSLWantWriteError\n",
      "        SSLWantReadError\n",
      "        SSLSyscallError\n",
      "        SSLEOFError\n",
      "      Error\n",
      "        SameFileError\n",
      "      SpecialFileError\n",
      "      ExecError\n",
      "      ReadError\n",
      "      URLError\n",
      "        HTTPError\n",
      "        ContentTooShortError\n",
      "      BadGzipFile\n",
      "    EOFError\n",
      "      IncompleteReadError\n",
      "    RuntimeError\n",
      "      RecursionError\n",
      "      NotImplementedError\n",
      "        ZMQVersionError\n",
      "        StdinNotImplementedError\n",
      "      _DeadlockError\n",
      "      BrokenBarrierError\n",
      "      BrokenExecutor\n",
      "        BrokenThreadPool\n",
      "      SendfileNotAvailableError\n",
      "      ExtractionError\n",
      "      VariableError\n",
      "    NameError\n",
      "      UnboundLocalError\n",
      "    AttributeError\n",
      "      FrozenInstanceError\n",
      "    SyntaxError\n",
      "      IndentationError\n",
      "        TabError\n",
      "    LookupError\n",
      "      IndexError\n",
      "      KeyError\n",
      "        NoSuchKernel\n",
      "        UnknownBackend\n",
      "      CodecRegistryError\n",
      "    ValueError\n",
      "      UnicodeError\n",
      "        UnicodeEncodeError\n",
      "        UnicodeDecodeError\n",
      "        UnicodeTranslateError\n",
      "      UnsupportedOperation\n",
      "      JSONDecodeError\n",
      "      SSLCertVerificationError\n",
      "      Error\n",
      "      UnsupportedDigestmodError\n",
      "      IllegalMonthError\n",
      "      IllegalWeekdayError\n",
      "      ParserError\n",
      "      ClassNotFound\n",
      "      ClipboardEmpty\n",
      "      MessageDefect\n",
      "        NoBoundaryInMultipartDefect\n",
      "        StartBoundaryNotFoundDefect\n",
      "        CloseBoundaryNotFoundDefect\n",
      "        FirstHeaderLineIsContinuationDefect\n",
      "        MisplacedEnvelopeHeaderDefect\n",
      "        MissingHeaderBodySeparatorDefect\n",
      "        MultipartInvariantViolationDefect\n",
      "        InvalidMultipartContentTransferEncodingDefect\n",
      "        UndecodableBytesDefect\n",
      "        InvalidBase64PaddingDefect\n",
      "        InvalidBase64CharactersDefect\n",
      "        InvalidBase64LengthDefect\n",
      "        HeaderDefect\n",
      "          InvalidHeaderDefect\n",
      "          HeaderMissingRequiredValue\n",
      "          NonPrintableDefect\n",
      "          ObsoleteHeaderDefect\n",
      "          NonASCIILocalPartDefect\n",
      "          InvalidDateDefect\n",
      "      MacroToEdit\n",
      "      InvalidFileException\n",
      "      UnequalIterablesError\n",
      "      InvalidVersion\n",
      "      _InvalidELFFileHeader\n",
      "      InvalidWheelFilename\n",
      "      InvalidSdistFilename\n",
      "      InvalidSpecifier\n",
      "      InvalidMarker\n",
      "      UndefinedComparison\n",
      "      UndefinedEnvironmentName\n",
      "      InvalidRequirement\n",
      "        RequirementParseError\n",
      "      InvalidVersion\n",
      "    AssertionError\n",
      "    ArithmeticError\n",
      "      FloatingPointError\n",
      "      OverflowError\n",
      "      ZeroDivisionError\n",
      "        DivisionByZero\n",
      "        DivisionUndefined\n",
      "      DecimalException\n",
      "        Clamped\n",
      "        Rounded\n",
      "          Underflow\n",
      "          Overflow\n",
      "        Inexact\n",
      "          Underflow\n",
      "          Overflow\n",
      "        Subnormal\n",
      "          Underflow\n",
      "        DivisionByZero\n",
      "        FloatOperation\n",
      "        InvalidOperation\n",
      "          ConversionSyntax\n",
      "          DivisionImpossible\n",
      "          DivisionUndefined\n",
      "          InvalidContext\n",
      "    SystemError\n",
      "      CodecRegistryError\n",
      "    ReferenceError\n",
      "    MemoryError\n",
      "    BufferError\n",
      "    Warning\n",
      "      UserWarning\n",
      "        GetPassWarning\n",
      "        FormatterWarning\n",
      "      EncodingWarning\n",
      "      DeprecationWarning\n",
      "        ProvisionalWarning\n",
      "      PendingDeprecationWarning\n",
      "      SyntaxWarning\n",
      "      RuntimeWarning\n",
      "        ProactorSelectorThreadWarning\n",
      "        UnknownTimezoneWarning\n",
      "        PEP440Warning\n",
      "      FutureWarning\n",
      "        ProvisionalCompleterWarning\n",
      "      ImportWarning\n",
      "      UnicodeWarning\n",
      "      BytesWarning\n",
      "      ResourceWarning\n",
      "      DeprecatedTzFormatWarning\n",
      "      PkgResourcesDeprecationWarning\n",
      "    _OptionError\n",
      "    _Error\n",
      "    error\n",
      "    Verbose\n",
      "    Error\n",
      "    SubprocessError\n",
      "      CalledProcessError\n",
      "      TimeoutExpired\n",
      "    TokenError\n",
      "    StopTokenizing\n",
      "    ClassFoundException\n",
      "    EndOfBlock\n",
      "    TraitError\n",
      "    Error\n",
      "    Error\n",
      "      CancelledError\n",
      "      TimeoutError\n",
      "      InvalidStateError\n",
      "    _GiveupOnSendfile\n",
      "    error\n",
      "    Incomplete\n",
      "    TimeoutError\n",
      "    InvalidStateError\n",
      "    LimitOverrunError\n",
      "    QueueEmpty\n",
      "    QueueFull\n",
      "    Empty\n",
      "    Full\n",
      "    ArgumentError\n",
      "    ZMQBaseError\n",
      "      ZMQError\n",
      "        ContextTerminated\n",
      "        Again\n",
      "        InterruptedSystemCall\n",
      "      ZMQBindError\n",
      "      NotDone\n",
      "    PickleError\n",
      "      PicklingError\n",
      "      UnpicklingError\n",
      "    _Stop\n",
      "    ArgumentError\n",
      "    ArgumentTypeError\n",
      "    ConfigError\n",
      "      ConfigLoaderError\n",
      "        ArgumentError\n",
      "      ConfigFileNotFound\n",
      "    ConfigurableError\n",
      "      MultipleInstanceError\n",
      "    ApplicationError\n",
      "    error\n",
      "    TimeoutError\n",
      "    error\n",
      "    ReturnValueIgnoredError\n",
      "    KeyReuseError\n",
      "    UnknownKeyError\n",
      "    LeakedCallbackError\n",
      "    BadYieldError\n",
      "    ReturnValueIgnoredError\n",
      "    Return\n",
      "    InvalidPortNumber\n",
      "    error\n",
      "    LZMAError\n",
      "    RegistryError\n",
      "    _GiveupOnFastCopy\n",
      "    Error\n",
      "      NoSectionError\n",
      "      DuplicateSectionError\n",
      "      DuplicateOptionError\n",
      "      NoOptionError\n",
      "      InterpolationError\n",
      "        InterpolationMissingOptionError\n",
      "        InterpolationSyntaxError\n",
      "        InterpolationDepthError\n",
      "      ParsingError\n",
      "        MissingSectionHeaderError\n",
      "    NoIPAddresses\n",
      "    BadZipFile\n",
      "    LargeZipFile\n",
      "    BadEntryPoint\n",
      "    NoSuchEntryPoint\n",
      "    DuplicateKernelError\n",
      "    ErrorDuringImport\n",
      "    NotOneValueFound\n",
      "    CannotEval\n",
      "    OptionError\n",
      "    BdbQuit\n",
      "    Restart\n",
      "    ExceptionPexpect\n",
      "      EOF\n",
      "      TIMEOUT\n",
      "    PtyProcessError\n",
      "    FindCmdError\n",
      "    HomeDirError\n",
      "    ProfileDirError\n",
      "    IPythonCoreError\n",
      "      TryNext\n",
      "      UsageError\n",
      "      StdinNotImplementedError\n",
      "    InputRejected\n",
      "    GetoptError\n",
      "    ErrorToken\n",
      "    PrefilterError\n",
      "    AliasError\n",
      "      InvalidAliasError\n",
      "    Error\n",
      "      InterfaceError\n",
      "      DatabaseError\n",
      "        InternalError\n",
      "        OperationalError\n",
      "        ProgrammingError\n",
      "        IntegrityError\n",
      "        DataError\n",
      "        NotSupportedError\n",
      "    Warning\n",
      "    SpaceInInput\n",
      "    DOMException\n",
      "      IndexSizeErr\n",
      "      DomstringSizeErr\n",
      "      HierarchyRequestErr\n",
      "      WrongDocumentErr\n",
      "      InvalidCharacterErr\n",
      "      NoDataAllowedErr\n",
      "      NoModificationAllowedErr\n",
      "      NotFoundErr\n",
      "      NotSupportedErr\n",
      "      InuseAttributeErr\n",
      "      InvalidStateErr\n",
      "      SyntaxErr\n",
      "      InvalidModificationErr\n",
      "      NamespaceErr\n",
      "      InvalidAccessErr\n",
      "      ValidationErr\n",
      "    ValidationError\n",
      "    EditReadOnlyBuffer\n",
      "    _Retry\n",
      "    InvalidLayoutError\n",
      "    HeightIsUnknownError\n",
      "    ParserSyntaxError\n",
      "    InternalParseError\n",
      "    _PositionUpdatingFinished\n",
      "    SimpleGetItemNotFound\n",
      "    UncaughtAttributeError\n",
      "    HasNoContext\n",
      "    ParamIssue\n",
      "    _JediError\n",
      "      InternalError\n",
      "      WrongVersion\n",
      "      RefactoringError\n",
      "    OnErrorLeaf\n",
      "    InvalidPythonEnvironment\n",
      "    MessageError\n",
      "      MessageParseError\n",
      "        HeaderParseError\n",
      "        BoundaryError\n",
      "      MultipartConversionError\n",
      "      CharsetError\n",
      "    Error\n",
      "    HTTPException\n",
      "      NotConnected\n",
      "      InvalidURL\n",
      "      UnknownProtocol\n",
      "      UnknownTransferEncoding\n",
      "      UnimplementedFileMode\n",
      "      IncompleteRead\n",
      "      ImproperConnectionState\n",
      "        CannotSendRequest\n",
      "        CannotSendHeader\n",
      "        ResponseNotReady\n",
      "      BadStatusLine\n",
      "        RemoteDisconnected\n",
      "      LineTooLong\n",
      "    InteractivelyDefined\n",
      "    KillEmbedded\n",
      "    Error\n",
      "      NoSuchProcess\n",
      "        ZombieProcess\n",
      "      AccessDenied\n",
      "      TimeoutExpired\n",
      "    _Ipv6UnsupportedError\n",
      "    QueueEmpty\n",
      "    QueueFull\n",
      "    DebuggerInitializationError\n",
      "    ExpatError\n",
      "    Error\n",
      "      ProtocolError\n",
      "      ResponseError\n",
      "      Fault\n",
      "    ParseBaseException\n",
      "      ParseException\n",
      "      ParseFatalException\n",
      "        ParseSyntaxException\n",
      "    RecursiveGrammarException\n",
      "    ResolutionError\n",
      "      VersionConflict\n",
      "        ContextualVersionConflict\n",
      "      DistributionNotFound\n",
      "      UnknownExtra\n",
      "    _Error\n",
      "    UnableToResolveVariableException\n",
      "    InvalidTypeInArgsException\n",
      "    CustomError\n",
      "    InvalidAgeError\n",
      "    InvalidAgeError\n",
      "    CustomError\n",
      "  GeneratorExit\n",
      "  SystemExit\n",
      "  KeyboardInterrupt\n",
      "  CancelledError\n",
      "  AbortThread\n"
     ]
    }
   ],
   "source": [
    "import builtins\n",
    "\n",
    "def print_exception_hierarchy(base_exception, depth=0):\n",
    "    indent = \"  \" * depth\n",
    "    print(indent + base_exception.__name__)\n",
    "    \n",
    "    # Get the subclasses of the base_exception\n",
    "    subclasses = base_exception.__subclasses__()\n",
    "    \n",
    "    for subclass in subclasses:\n",
    "        print_exception_hierarchy(subclass, depth + 1)\n",
    "\n",
    "print(\"Python Exception Hierarchy:\")\n",
    "print_exception_hierarchy(BaseException)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d61ffaef-0666-4f52-8c33-2e46d663026a",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "markdown",
   "id": "270adc8f-3b41-4d5c-a1bb-880ae11ceb40",
   "metadata": {},
   "source": [
    "Q3. What errors are defined in the ArithmeticError class? Explain any two with an example.\n",
    "\n",
    "ANS:\n",
    "\n",
    "The ArithmeticError class in Python is a base class for exceptions that are related to arithmetic operations. It serves as a parent class for various arithmetic-related exception classes. Two common exceptions derived from ArithmeticError are ZeroDivisionError and OverflowError. "
   ]
  },
  {
   "cell_type": "markdown",
   "id": "8a3ab404-3069-4fb5-90b8-6ef657976ca6",
   "metadata": {},
   "source": [
    "###  ZeroDivisionError:\n",
    "\n",
    "ZeroDivisionError is raised when you attempt to divide a number by zero, which is mathematically undefined."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 30,
   "id": "91bf6d85-8590-4bd5-86a4-330f7a77f4e6",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error: division by zero\n"
     ]
    }
   ],
   "source": [
    "try:\n",
    "    numerator = 10\n",
    "    denominator = 0\n",
    "    result = numerator / denominator  # Attempting to divide by zero\n",
    "except ZeroDivisionError as e:\n",
    "    print(f\"Error: {e}\")\n",
    "else:\n",
    "    print(\"Result:\", result)\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "4e5e2afd-7e44-49bd-80e8-61a314bbd81e",
   "metadata": {},
   "source": [
    "### OverflowError:\n",
    "\n",
    "OverflowError is raised when an arithmetic operation exceeds the limits of the data type being used.\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 31,
   "id": "3bbd109c-924e-42f9-8b66-c5cb90398ad1",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Result: 10715086071862673209484250490600018105614048117055336074437503883703510511249361224931983788156958581275946729175531468251871452856923140435984577574698574803934567774824230985421074605062371141877954182153046474983581941267398767559165543946077062914571196477686542167660429831652624386837205668069376\n"
     ]
    }
   ],
   "source": [
    "try:\n",
    "    large_number = 2 ** 1000  # Attempting to calculate a very large power of 2\n",
    "except OverflowError as e:\n",
    "    print(f\"Error: {e}\")\n",
    "else:\n",
    "    print(\"Result:\", large_number)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6994d018-de2b-42d1-aef7-64576230225e",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "markdown",
   "id": "b4cf7562-0a5c-49be-807e-f0ca0d3da2c0",
   "metadata": {},
   "source": [
    "Q4. Why LookupError class is used? Explain with an example KeyError and IndexError.\n",
    "\n",
    "ANS:\n",
    "\n",
    "The LookupError class in Python is a base class for exceptions that occur when you try to access an element or key in a collection (such as a list or dictionary) and the element/key does not exist. LookupError itself is not meant to be directly raised; instead, it serves as a parent class for more specific lookup-related exceptions, such as KeyError and IndexError.\n",
    "\n",
    "\n",
    "\n",
    "### KeyError:\n",
    "\n",
    "KeyError is raised when you try to access a dictionary with a key that does not exist in the dictionary."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 33,
   "id": "c38ed3c1-7100-48a0-8f09-8f2b37be9f52",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "KeyError: 'David'\n"
     ]
    }
   ],
   "source": [
    "student_grades = {\"Alice\": 85, \"Bob\": 92, \"Charlie\": 78}\n",
    "\n",
    "try:\n",
    "    grade = student_grades[\"David\"]\n",
    "    print(f\"David's grade: {grade}\")\n",
    "except KeyError as e:\n",
    "    print(f\"KeyError: {e}\")\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "626543d0-e7dd-4816-986d-99e7d2f7ad8d",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "markdown",
   "id": "a51dd9e2-d463-4abb-b3d7-5a11aaeffb29",
   "metadata": {},
   "source": [
    "### IndexError:\n",
    "\n",
    "IndexError is raised when you try to access an element in a sequence (e.g., a list or tuple) using an index that is out of range."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 34,
   "id": "4019998e-d6eb-4eb0-a7d3-866ec3e6f40d",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "IndexError: list index out of range\n"
     ]
    }
   ],
   "source": [
    "my_list = [10, 20, 30, 40, 50]\n",
    "\n",
    "try:\n",
    "    value = my_list[10]\n",
    "    print(f\"Value at index 10: {value}\")\n",
    "except IndexError as e:\n",
    "    print(f\"IndexError: {e}\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d1dbf36f-6993-4549-9908-a725e0cd7ced",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "markdown",
   "id": "4ca4bab6-94e2-4cce-88bb-57a19eacaa81",
   "metadata": {},
   "source": [
    "Q5. Explain ImportError. What is ModuleNotFoundError?\n",
    "\n",
    "ANS:  \n",
    "\n",
    "ImportError and ModuleNotFoundError are both exceptions in Python that occur when there is an issue with importing modules or packages. However, there are differences between them:\n",
    "\n",
    "### ImportError:\n",
    "\n",
    "ImportError is a base class for exceptions related to importing modules. It is raised when Python encounters an issue while trying to import a module or when there are problems within the imported module.\n",
    "\n",
    "ImportError can have various subtypes, such as AttributeError, NameError, or ModuleNotFoundError, depending on the specific issue that occurred during the import."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 35,
   "id": "e7886a77-b77d-4eea-a95c-833151ee7d0a",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "ImportError: No module named 'non_existent_module'\n"
     ]
    }
   ],
   "source": [
    "try:\n",
    "    import non_existent_module\n",
    "except ImportError as e:\n",
    "    print(f\"ImportError: {e}\")\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "4ef29022-9080-4e02-967b-b83528f59db7",
   "metadata": {},
   "source": [
    "### ModuleNotFoundError:\n",
    "\n",
    "ModuleNotFoundError is a specific subtype of ImportError that is raised when Python cannot find the module that you are trying to import. This exception was introduced in Python 3.6 to provide more specific and informative error messages."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 36,
   "id": "dd6c8853-9e53-45d1-bc87-7b8ef16d34b9",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "ModuleNotFoundError: No module named 'non_existent_module'\n"
     ]
    }
   ],
   "source": [
    "try:\n",
    "    import non_existent_module\n",
    "except ModuleNotFoundError as e:\n",
    "    print(f\"ModuleNotFoundError: {e}\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "3cbb065d-68ab-4405-998d-3f8370664a70",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "markdown",
   "id": "8f00b589-d98a-4e64-a601-955cd9c14386",
   "metadata": {},
   "source": [
    "Q6. List down some best practices for exception handling in python.\n",
    "\n",
    "ANS:\n",
    "\n",
    "Here are some best practices for effective exception handling in Python:\n",
    "\n",
    "1. Use Specific Exceptions: Catch specific exceptions whenever possible rather than catching generic ones like Exception or BaseException. This allows you to handle errors more precisely and prevents unintended side effects.\n",
    "\n",
    "2. Keep Exception Blocks Short: Limit the amount of code within your try-except blocks. Only include the code that might raise an exception, and avoid wrapping large sections of code in a single try block.\n",
    "\n",
    "3. Handle Exceptions Appropriately: Handle exceptions appropriately based on the specific error. Avoid simply catching exceptions and ignoring them, as this can hide bugs and make debugging difficult.\n",
    "\n",
    "4. Use else Clause: Use the else clause in a try-except block to include code that should execute when no exceptions are raised. This can help improve code readability.\n",
    "\n",
    "5. Use finally for Cleanup: When you need to ensure certain actions (e.g., closing files or releasing resources) always occur, use the finally block. It executes regardless of whether an exception was raised or not.\n",
    "\n",
    "6. Avoid Bare except: Avoid using a bare except clause (i.e., except:) without specifying the exception type. It can catch unexpected exceptions and make debugging difficult. Be explicit about which exceptions you're handling.\n",
    "\n",
    "7. Use Context Managers (with Statements): Utilize context managers (e.g., with statements) for resource management, like opening and closing files. Context managers automatically handle cleanup.\n",
    "\n",
    "8. Log Exceptions: Log exceptions with a logging library (e.g., logging) to keep track of errors and their context. Logging can aid in debugging and troubleshooting.\n",
    "\n",
    "9. Reraise Exceptions Carefully: If you need to catch an exception but still want it to propagate up the call stack, you can re-raise it using raise without any arguments. This is helpful for debugging and preserving the original exception's information.\n",
    "\n",
    "10. Custom Exceptions: Create custom exception classes when you need to handle application-specific errors. This improves code readability and allows you to provide meaningful error messages.\n",
    "\n",
    "11. Use try-except Around External Dependencies: When interacting with external resources or services, wrap those interactions in try-except blocks to gracefully handle issues and provide feedback to the user.\n",
    "\n",
    "12. Don't Suppress Errors: Avoid suppressing errors by catching exceptions and not doing anything with them. If an error occurs, it's often best to let it propagate so you can diagnose and fix the underlying issue.\n",
    "\n",
    "13. Document Exception Handling: Document your exception handling approach, especially if it's non-trivial. Comments or docstrings can help other developers understand your code's error-handling strategy."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "61e64555-a6c1-477c-a7d6-a5e379517874",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
